BACKBONE:
  MODEL_TYPE: "convnext"
  OUT_CHANNELS: 128
  DROP_PATH: 0.3
DATASETS:
  TRAIN: ("crestereo", "in_stereo2k", "eth3d")
  MUL: (1, 10, 1000)
  CROP_SIZE: [384, 512]
  TEST: ("kitti_2012_trainval", "kitti_2015_trainval", "eth3d", "middlebury_Q")
TEST:
  EVAL_THRESH: (['3.0'], ['3.0'], ['1.0'], ['2.0'])
  EVAL_MAX_DISP: [null, null, null, 1000]
  EVAL_ONLY_VALID: (True, True, True, False)
  EVAL_PROP: (True, True, True, True)
SOLVER:
  NO_RESUME_OPTIMIZER: True
  IMS_PER_BATCH: 8
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 100000
  MAX_DISP: 256