SOLVER:
  NO_RESUME_OPTIMIZER: True
  IMS_PER_BATCH: 4
  MAX_ITER: 39000
  BASE_LR: 0.0002
  CHECKPOINT_PERIOD: 10000
  MAX_DISP: 384
  LOSS_TYPE: "SMOOTH_L1"
DATASETS:
  TRAIN: ("kitti_mix",)
  CROP_SIZE: [304, 1152]
  TEST: ("kitti_2015_val",)
TEST:
  EVAL_PERIOD: 500
  EVAL_MAX_DISP: [null]
OMNIDEPTH:
  ENCODER_VIT: "vitl"
  RECURRENT_LOSS_WEIGHT: 1.0
  RECURRENT_LOSS_GAMMA: 0.8
BACKBONE:
  MODEL_TYPE: "convnext"
  OUT_CHANNELS: 128
  DROP_PATH: 0.3
DPN:
  NUM_PROPOSALS: 4
NMP:
  REFINE_WINDOW_SIZE: 4
