BACKBONE:
  MODEL_TYPE: "convnext"
  OUT_CHANNELS: 128
  DROP_PATH: 0.2
OMNIDEPTH:
  ENCODER_VIT: "vitl"
  RECURRENT_LOSS_WEIGHT: 1.0
  RECURRENT_LOSS_GAMMA: 0.8
DPN:
  NUM_PROPOSALS: 2
NMP:
  REFINE_WINDOW_SIZE: 4