BACKBONE:
  MODEL_TYPE: "convnext"
  OUT_CHANNELS: 128
  DROP_PATH: 0.3
DPN:
  NUM_PROPOSALS: 2
NMP:
  REFINE_WINDOW_SIZE: 4
DATASETS:
  TRAIN: ("sceneflow", "falling_things", "tartan_air", "carla_highres", "crestereo", "in_stereo2k", "middlebury_2014", "middlebury_2021", "middlebury_H")
  MUL: (1, 1, 1, 50, 1, 50, 200, 200, 200)
  CROP_SIZE: [384, 512]
  TEST: ("kitti_2012_trainval", "kitti_2015_trainval", "eth3d", "middlebury_Q")
TEST:
  EVAL_THRESH: (['3.0'], ['3.0'], ['1.0'], ['2.0'])
  EVAL_MAX_DISP: [null, null, null, 1000]
  EVAL_ONLY_VALID: (True, True, True, False)
  EVAL_PROP: (True, True, True, True)
SOLVER:
  IMS_PER_BATCH: 8
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 300000
  MAX_DISP: 256